language: julia
os:
    - osx
    - linux
    - windows
julia:
    - 1
    - nightly

jobs:
    allow_failures:
        - julia: nightly
    include:
        - stage: "Documentation"
          julia: 1
          os: linux
          script:
            - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                   Pkg.instantiate()'
            - julia --project=docs/ docs/make.jl
          after_success: skip

addons:
    apt:
      packages:
        - python3-matplotlib

after_success:
    - julia -e 'import Pkg; cd(Pkg.dir("CollectiveSpins")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'import Pkg; cd(Pkg.dir("CollectiveSpins")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
    - julia -e 'import Pkg; Pkg.add("Documenter")'
    - julia -e 'import Pkg; cd(Pkg.dir("CollectiveSpins")); include(joinpath("docs", "make.jl"))'

notifications:
    email: false
